# Special colors
background #29282B
# background #ffffff
foreground #FFEFD3
# foreground #000000

# Black
color0  #39393B
color8  #AD9C80

# Red
color1  #9E1B17
# color1  #3C352E
color9  #50473E

# Green
color2  #F6E0B7
# color2 #000000
color10 #904638

# Yellow
color3  #6F573D
color11 #947451

# Blue
color4  #581D97
# color4  #B0392F
color12 #EB4C3F

# Magenta
color5  #BF7446
color13 #FF9B5D

# Cyan
color6  #BF9D60
color14 #FFD180

# White
color7  #F6E0B7
color15 #F6E0B7
