# Special colors
background #333335
# background #ffffff
foreground #F8F7FB
# foreground #000000

# Black
color0  #434346
color8  #A5A4A8

# Red
color1  #961824
# color1  #2C3048
color9  #3B4060

# Green
color2  #ECEBF1
# color2 #000000
color10 #656B7F

# Yellow
color3  #6A687C
color11 #8D8AA5

# Blue
color4  #4044C7
# color4  #81878E
color12 #ACB4BE

# Magenta
color5  #9289A6
color13 #C2B6DD

# Cyan
color6  #B0AEB6
color14 #EAE8F3

# White
color7  #ECEBF1
color15 #ECEBF1
